DROP DATABASE IF EXISTS x8i76z9ke00xwl4s;

CREATE DATABASE x8i76z9ke00xwl4s;

CREATE TABLE highscores (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    highscore_name VARCHAR(30) NOT NULL,
    devoured BOOLEAN DEFAULT false,
);
